import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const stage = read("src/viewer-panels/stage.ts");
const panel = read("src/viewer-panels/designPanel.ts");
const wizard = read("src/viewer-generation-wizard.ts");
const spec = read("src/viewer-generation-spec.ts");
const runner = read("src/viewer-generation-runner.ts");
const app = read("src/app.ts");
const css = read("src/styles/viewer/stage-console.css");

assert.match(stage, /role="dialog" aria-modal="true"/);
assert.equal((stage.match(/data-generation-primary-tab=/g) ?? []).length, 3);
assert.match(stage, /aria-controls="viewer-generation-page-source"/);
assert.match(stage, /aria-controls="viewer-generation-page-strategy"/);
assert.match(stage, /aria-controls="viewer-generation-page-output"/);
assert.equal((panel.match(/data-generation-strategy-tab=/g) ?? []).length, 1, "strategy tabs are generated by one shared renderer");
for (const page of ["assets", "structure", "furniture", "notes", "matrix"]) {
  assert.match(panel, new RegExp(`strategyTab\\("${page}"`));
  assert.match(panel, new RegExp(`data-generation-strategy-panel=\\"${page}\\"`));
}
assert.match(wizard, /ArrowRight/);
assert.match(wizard, /ArrowLeft/);
assert.match(wizard, /event\.key === "Escape"/);
assert.match(wizard, /focusableElements/);
assert.match(spec, /sourceMode: "reference_annotation" \| "graph_template"/);
assert.match(spec, /sourceMode === "reference_annotation"/);
assert.match(spec, /scenario\?\.template_patch/);
assert.match(spec, /graph_template_id: spec\.graphTemplateId/);
assert.doesNotMatch(spec, /DEFAULT_GRAPH_TEMPLATE_ID|hkust_gz_gate/);
assert.match(runner, /cancelGenerationJob/);
assert.match(runner, /onLoadResult/);
assert.match(runner, /payload\?\.operations\?\.slice\(-3\)/);
assert.match(app, /buildGenerationRequestSpec/);
assert.match(app, /generationRunner\.run\(spec\)/);
assert.match(
  app,
  /onLoadResult:[\s\S]*?loadLayoutSelection\(layoutPath,[\s\S]*?frameSceneOverview\(\)/,
  "a generated OSM scene must open in a fitted overview instead of an eye-level horizon view",
);
assert.doesNotMatch(app, /workflowSnapshot\.normalized\s*\?\s*workflowBridge\.runGeneration/);
assert.match(css, /grid-template-rows: minmax\(0, 1fr\) auto/);
assert.match(css, /\.viewer-generation-primary-panel\[hidden\]/);
assert.match(css, /overflow-x: auto/);

console.log("generation wizard contract: ok");
