import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const stage = read("src/viewer-panels/stage.ts");
const panel = read("src/viewer-panels/designPanel.ts");
const wizard = read("src/viewer-generation-wizard.ts");
const spec = read("src/viewer-generation-spec.ts");
const runner = read("src/viewer-generation-runner.ts");
const app = read("src/app.ts");
const designScenario = read("src/viewer-design-scenario-controller.ts");
const viewerRuntime = `${app}\n${designScenario}`;
const parameterDesign = read("src/viewer-parameter-design.ts");
const css = read("src/styles/viewer/stage-console.css");

assert.match(stage, /role="dialog" aria-modal="true"/);
assert.equal((stage.match(/data-generation-primary-tab=/g) ?? []).length, 3);
assert.match(stage, /aria-controls="viewer-generation-page-source"/);
assert.match(stage, /aria-controls="viewer-generation-page-strategy"/);
assert.match(stage, /aria-controls="viewer-generation-page-output"/);
assert.equal((panel.match(/data-generation-strategy-tab=/g) ?? []).length, 1, "strategy tabs are generated by one shared renderer");
for (const page of ["skeleton", "furniture"]) {
  assert.match(panel, new RegExp(`strategyTab\\("${page}"`));
  assert.match(panel, new RegExp(`data-generation-strategy-panel=\\"${page}\\"`));
}
assert.doesNotMatch(panel, /strategyTab\("assets"/, "asset permissions are no longer a visible generation step");
for (const removed of ["方案矩阵", "补充要求", "让 AI 建议参数", "街道家具设计目标", "参数化方案</span>"]) {
  assert.doesNotMatch(panel, new RegExp(removed));
}
assert.doesNotMatch(panel, /生成 3 个轻微变化方案/);
assert.match(panel, /viewer-parameter-skeleton-controls/);
assert.match(panel, /viewer-parameter-furniture-controls/);
assert.match(panel, /<aside id="viewer-design-panel"[\s\S]*viewer-parameter-summary-board[\s\S]*<\/aside>/);
assert.match(panel, /生成 1 个确定性场景版本/);
assert.match(viewerRuntime, /generation_mode: "parametric"|generationOptions\(\)/);
assert.match(viewerRuntime, /variantCount: 1/);
assert.match(parameterDesign, /roadgen3d\.street-design-parameters\.v2/);
assert.match(parameterDesign, /\/api\/design\/parameter-controls/);
assert.match(parameterDesign, /generation_mode: "parametric"/);
assert.match(parameterDesign, /skip_llm: true/);
assert.match(parameterDesign, /knowledge_source: "none"/);
assert.doesNotMatch(parameterDesign, /parameter-proposals|parameter-profiles|llm_suggestion/);
assert.match(wizard, /ArrowRight/);
assert.match(wizard, /ArrowLeft/);
assert.match(wizard, /event\.key === "Escape"/);
assert.match(wizard, /focusableElements/);
assert.match(spec, /sourceMode: "reference_annotation" \| "graph_template"/);
assert.match(spec, /sourceMode === "reference_annotation"/);
assert.match(spec, /scenario\?\.template_patch/);
assert.match(spec, /graph_template_id: spec\.graphTemplateId/);
assert.match(spec, /!usesExplicitParameters \? \{ preset_id: spec\.presetId \} : \{\}/);
assert.doesNotMatch(spec, /DEFAULT_GRAPH_TEMPLATE_ID|hkust_gz_gate/);
assert.match(runner, /cancelGenerationJob/);
assert.match(runner, /onLoadResult/);
assert.match(runner, /payload\?\.operations\?\.slice\(-3\)/);
assert.match(runner, /function explainGenerationFailure/);
assert.match(runner, /场景生成失败，请查看下方诊断/);
assert.doesNotMatch(runner, /没有方案生成成功/);
assert.match(viewerRuntime, /buildGenerationRequestSpec/);
assert.match(viewerRuntime, /generationRunner\.run\(spec\)/);
assert.match(
  viewerRuntime,
  /onLoadResult:[\s\S]*?loadLayoutSelection\(layoutPath,[\s\S]*?frameSceneOverview\(\)/,
  "a generated OSM scene must open in a fitted overview instead of an eye-level horizon view",
);
assert.doesNotMatch(viewerRuntime, /workflowSnapshot\.normalized\s*\?\s*workflowBridge\.runGeneration/);
assert.match(css, /grid-template-rows: minmax\(0, 1fr\) auto/);
assert.match(css, /\.viewer-generation-primary-panel\[hidden\]/);
assert.match(css, /overflow-x: auto/);
assert.match(css, /\.viewer-generation-strategy-workspace \{[\s\S]*overflow-y: auto/);
assert.match(css, /\.viewer-generation-strategy-panel \{[\s\S]*height: auto;[\s\S]*overflow: visible/);

console.log("generation wizard contract: ok");
