import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const workflow = read("src/workflow-controller.ts");
const pipeline = read("src/professional-pipeline.ts");
const routeIsland = read("src/react/RouteIsland.tsx");
const app = read("src/app.ts");
const assetEditor = read("src/asset-editor.ts");
const stage = read("src/viewer-panels/stage.ts");
const designPanel = read("src/viewer-panels/designPanel.ts");
const baseline = read("src/professional-baseline-coordinator.ts");
const publicProject = read("src/professional-public-project.ts");
const courseApi = read("src/course-api.ts");
const scenarios = read("src/viewer-scenario-workbench.ts");
const settingsPanel = read("src/viewer-settings-panel.ts");
const compareMode = read("src/compare-mode.ts");
const scenarioStyles = read("src/styles/viewer/professional-scenarios.css");
const parameterStyles = read("src/styles/viewer/parameter-design.css");
const sceneGraph = read("src/scene-graph.ts");
const sceneGraphShell = read("src/scene-graph/shell.ts");
const entryIntent = read("src/professional-entry-intent.ts");
const nextAction = read("src/professional-next-action.ts");
const publicPanels = read("src/professional-account-panels.ts");
const sceneGraphToolbar = read("src/styles/scene-graph/toolbar-stage.css");

assert.match(workflow, /type AssetPreparationChoice = "current_manifest" \| "default_transparent_massing" \| null/);
assert.match(workflow, /export type AssetCandidateManifest/);
assert.match(workflow, /export type AssetPreparationState/);
assert.match(workflow, /mode: "candidate_manifests"/);
assert.match(workflow, /function defaultAssetPreparationState/);
assert.match(workflow, /if \(!stored\) return defaultAssetPreparationState\(\)/);
assert.match(workflow, /normalizeAssetPreparationState\(JSON\.parse\(stored\)\) \?\? defaultAssetPreparationState\(\)/);
assert.match(workflow, /type SceneReviewStatus = "not_available" \| "pending" \| "changes_requested" \| "accepted"/);
assert.match(workflow, /export type WorkflowBaselineRun/);
assert.match(workflow, /sceneSourceRevision/);
assert.match(workflow, /setGeneratedScene[\s\S]*sceneReviewStatus: "pending"/);
assert.match(workflow, /setSceneRevision[\s\S]*sceneReviewStatus: "pending"/);
assert.match(pipeline, /if \(snapshot\.sceneReviewStatus === "changes_requested"\) return "edit"/);
assert.match(pipeline, /snapshot\.sceneRef\?\.kind === "starter_demo"\) return "review"/);
assert.match(pipeline, /if \(snapshot\.sceneReviewStatus === "accepted" \|\| snapshot\.evaluation\) return "deliver"/);
assert.match(routeIsland, /01A/);
assert.doesNotMatch(routeIsland, /id: "prepare-assets"/);
assert.match(routeIsland, /storeProfessionalViewerTarget/);
assert.doesNotMatch(routeIsland, /model-input-audit/);
assert.doesNotMatch(routeIsland, /mountModelInputBrowser/);
assert.doesNotMatch(designPanel, /strategyTab\("assets"/);
assert.match(designPanel, /strategyTab\("skeleton"/);
assert.match(app, /building_representation = "transparent_massing"/);
assert.match(app, /setSceneReviewStatus\("accepted"\)/);
assert.match(app, /setSceneReviewStatus\("changes_requested"\)/);
assert.match(app, /button\.disabled = !hasCurrentWorkflowScene \|\| starterPreview/);
assert.match(pipeline, /professional\.review\.edit3d/);
assert.match(pipeline, /professional\.review\.edit2d/);
assert.doesNotMatch(pipeline, /viewer-result-review-assets/, "review must not send users to a separate asset search");
assert.match(assetEditor, /setAssetPreparation\(Object\.freeze\(\{/);
assert.match(assetEditor, /id: "asset-candidates"/);
assert.match(assetEditor, /DEFAULT_ASSET_MANIFEST_NAME = "real_assets_manifest\.jsonl"/);
assert.match(app, /candidate_asset_manifests/);
assert.match(designPanel, /viewer-generation-candidate-list/);
assert.match(baseline, /street_furniture_profile: "none"/);
assert.match(baseline, /amenity_coverage_mode: "off"/);
assert.match(baseline, /curated_street_assets_profile: "disabled"/);
assert.match(baseline, /building_representation: "transparent_massing"/);
assert.match(baseline, /skip_llm: true/);
assert.match(baseline, /randomSeed: 42/);
assert.match(baseline, /render_presentation_artifacts: false/);
assert.match(baseline, /capture_3d_views: false/);
assert.match(publicProject, /shortLabel = "A"/);
assert.match(publicProject, /revision\.id === latestBaseline\?\.id/, "only the latest OSM baseline must occupy lane A");
assert.match(publicProject, /shortLabel = `B\$\{humanIndex\}`/);
assert.match(publicProject, /shortLabel = `C\$\{candidateIndex\}`/);
assert.match(publicProject, /revision\.branch_kind === "ai_edit"/, "unknown revision kinds must not be misclassified as C");
assert.match(courseApi, /source_id\?: string \| null/);
assert.match(publicProject, /generation_mode: "parametric"/);
assert.match(publicProject, /goal_weights: goalWeights/);
assert.match(publicProject, /parent_revision_id: parentRevisionId/);
assert.match(publicProject, /canWrite: boolean/);
assert.match(publicProject, /parentRevision\.source_id \?\? sourcePayload\.items\[0\]\?\.id/);
assert.match(publicProject, /workflowHasCurrent2DSource/);
assert.match(publicProject, /\/api\/v1\/projects\/\$\{sceneRef\.projectId\}\/sources/);
assert.match(publicProject, /branch_kind === "human_edit"/);
assert.match(publicProject, /branch_kind === "baseline"/);
assert.match(publicProject, /prepareManualEdit/);
assert.match(publicProject, /copyProfessionalStarterToOwnedProject/);
assert.match(publicProject, /source_id: saved\.source\.id/);
assert.match(routeIsland, /copyStarterToProject/);
assert.match(publicPanels, /已载入公共项目的最新 3D 场景。/, "the public-project drawer must replace its loading text after a scene opens");
assert.match(app, /mode3dEl\.click\(\)[\s\S]*desktop-shell-modal-close[\s\S]*evaluationRunner\.run\(\)/, "accepting a result must close review, return to 3D browsing, and run evaluation automatically");
assert.doesNotMatch(app, /reviewAcceptEl[\s\S]{0,240}\[data-shell-tab="evaluate"\]/, "accepting a result must not open the evaluation dialog");
assert.match(app, /复制为我的项目/);
assert.match(app, /requestProfessionalOsmPicker\(\)/);
assert.match(entryIntent, /roadgen3d:professional-open-osm-picker/);
assert.match(sceneGraph, /consumeProfessionalOsmPickerRequest\(\)/);
assert.match(sceneGraph, /generationConfirmSummary\.innerHTML[\s\S]*shell\.sidebar\.close\(\)[\s\S]*generationConfirmDialog\.hidden = false/, "opening 03 generation configuration must close the input drawer first");
assert.match(sceneGraphToolbar, /\.scene-generation-confirm-dialog\s*\{[\s\S]*z-index: var\(--rg-overlay-z-modal\)/, "generation confirmation must layer above workbench drawers");
assert.match(sceneGraph, /workflow\.transition\("source"\)/);
assert.match(sceneGraph, /地图数据获取完成。下一步：在地图上选择一条重点道路。/);
assert.match(scenarios, /PROPERTIES \+ DIFFERENCE/);
assert.match(scenarios, /renderLane\("A", scenarios\)/);
assert.match(scenarios, /renderLane\("B", scenarios\)/);
assert.match(scenarios, /renderLane\("C", scenarios\)/);
assert.match(scenarios, /在主画布打开/);
assert.match(scenarios, /道路骨架/);
assert.match(scenarios, /街道家具/);
assert.match(scenarios, /data-scenario-action="generate"/);
assert.match(scenarios, /data-scenario-action="split"/);
assert.match(scenarios, /openSplitComparison/);
assert.match(app, /compareMode\.enterCompareSceneSet/);
assert.match(compareMode, /Promise<boolean>/, "the split engine must report whether scene loading succeeded");
assert.match(settingsPanel, /id="building-opacity"/);
assert.match(settingsPanel, /仅调整查看器中的建筑显示|viewer\.settings\.buildingOpacityHint/);
assert.match(app, /function applyBuildingOpacity/);
assert.match(app, /viewerOriginalTransparent/);
assert.match(scenarios, /data-scenario-weight="\$\{key\}"/);
assert.match(scenarios, /至少两个目标需大于 0/);
assert.match(scenarios, /three local variants/);
assert.match(scenarios, /not a global-optimum claim/);
assert.match(publicProject, /candidate_count: 3/);
assert.match(publicProject, /not a claim of global optimality/);
assert.match(publicProject, /selectedScenarioId: revision\.id/);
assert.match(scenarios, /scenario\.id === generated\.selectedScenarioId/);
assert.match(scenarios, /data-scenario-action="edit-2d"/);
assert.match(scenarios, /保留当前 OSM 研究区与已保存标注/);
assert.match(scenarios, /viewer-scenario-lane-action/);
assert.match(scenarios, /data-scenario-action="edit-3d"/);
assert.match(scenarios, /candidateReadiness/);
assert.match(scenarios, /前往 2D 标注，生成 A 基线/);
assert.match(scenarios, /未绑定可追溯的 2D 来源/);
assert.match(scenarios, /roadgen3d:scenario-revision-saved/);
assert.match(scenarioStyles, /grid-template-columns: minmax\(17rem, 1fr\) minmax\(0, 2fr\)/);
assert.match(scenarioStyles, /viewer-scenario-guide/);
assert.match(parameterStyles, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(app, /roadgen3d:scenario-revision-saved/);
assert.match(sceneGraph, /forward_drive_lane_count/);
assert.match(sceneGraph, /bike_lane_count/);
assert.match(sceneGraph, /bus_lane_count/);
assert.match(sceneGraph, /data-strip-field="width_m"/);
assert.match(sceneGraph, /setAnnotationDraft/);
assert.match(sceneGraph, /onNavigateProfessionalScene/);
assert.match(sceneGraph, /sceneMatchesCurrentAnnotation/);
assert.match(sceneGraphShell, /data-admin-source-tools\$\{advancedSourceToolsHidden\}/);
assert.match(sceneGraphShell, /scene-source-open-existing/);
assert.match(sceneGraphShell, /scene-source-open-annotation-tools/);
assert.match(sceneGraphShell, /标注作用：在道路横断面或功能区落点后，会保存为必需的 3D 街道家具实例/);
assert.match(sceneGraphShell, /scene-generation-confirm-dialog/);
assert.match(sceneGraphShell, /确认并进入生成配置/);
assert.match(sceneGraph, /openGenerationConfiguration/);
assert.match(sceneGraph, /osmBaseAnnotation/);
assert.match(workflow, /restoredOsmBaseAnnotation/);
assert.match(sceneGraphShell, /showAdvancedSourceTools\?: boolean/);
assert.match(routeIsland, /user\?\.system_role === "admin"/);
assert.match(routeIsland, /syncAdvancedSourceTools\(\)/);
assert.match(routeIsland, /showAdvancedSourceTools: showAdvancedSourceTools\(\)/);
assert.match(routeIsland, /adminButton\.hidden = !visible/);
assert.doesNotMatch(routeIsland, /professionalSession\.subscribe\(\(\) => \{\s*registerProfessionalNavigation\(\)/);
assert.doesNotMatch(routeIsland, /id: "generate"/);
assert.match(routeIsland, /id: "browse-3d"/);
assert.match(nextAction, /approvedSourceRevision !== snapshot\.sourceRevision/);
assert.match(nextAction, /sceneSourceRevision !== snapshot\.sourceRevision/);
assert.match(nextAction, /sceneReviewStatus !== "accepted"/);
assert.match(nextAction, /查看方案 A\/B\/C/);

console.log("professional Y-pipeline contract: ok");
