import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (path) => readFileSync(resolve(root, path), "utf8");

const workflow = read("src/workflow-controller.ts");
const pipeline = read("src/professional-pipeline.ts");
const routeIsland = read("src/react/RouteIsland.tsx");
const app = read("src/app.ts");
const assetEditor = read("src/asset-editor.ts");
const stage = read("src/viewer-panels/stage.ts");
const designPanel = read("src/viewer-panels/designPanel.ts");
const baseline = read("src/professional-baseline-coordinator.ts");
const publicProject = read("src/professional-public-project.ts");
const scenarios = read("src/viewer-scenario-workbench.ts");
const scenarioStyles = read("src/styles/viewer/professional-scenarios.css");
const sceneGraph = read("src/scene-graph.ts");
const sceneGraphShell = read("src/scene-graph/shell.ts");

assert.match(workflow, /type AssetPreparationChoice = "current_manifest" \| "default_transparent_massing" \| null/);
assert.match(workflow, /export type AssetCandidateManifest/);
assert.match(workflow, /export type AssetPreparationState/);
assert.match(workflow, /mode: "candidate_manifests"/);
assert.match(workflow, /function defaultAssetPreparationState/);
assert.match(workflow, /if \(!stored\) return defaultAssetPreparationState\(\)/);
assert.match(workflow, /normalizeAssetPreparationState\(JSON\.parse\(stored\)\) \?\? defaultAssetPreparationState\(\)/);
assert.match(workflow, /type SceneReviewStatus = "not_available" \| "pending" \| "changes_requested" \| "accepted"/);
assert.match(workflow, /export type WorkflowBaselineRun/);
assert.match(workflow, /sceneSourceRevision/);
assert.match(workflow, /setGeneratedScene[\s\S]*sceneReviewStatus: "pending"/);
assert.match(workflow, /setSceneRevision[\s\S]*sceneReviewStatus: "pending"/);
assert.match(pipeline, /if \(snapshot\.sceneReviewStatus === "changes_requested"\) return "edit"/);
assert.match(pipeline, /snapshot\.sceneRef\?\.kind === "starter_demo"\) return "review"/);
assert.match(pipeline, /if \(snapshot\.sceneReviewStatus === "accepted" \|\| snapshot\.evaluation\) return "deliver"/);
assert.match(routeIsland, /01A/);
assert.doesNotMatch(routeIsland, /id: "prepare-assets"/);
assert.match(routeIsland, /storeProfessionalViewerTarget/);
assert.doesNotMatch(routeIsland, /model-input-audit/);
assert.doesNotMatch(routeIsland, /mountModelInputBrowser/);
assert.doesNotMatch(designPanel, /strategyTab\("assets"/);
assert.match(designPanel, /strategyTab\("skeleton"/);
assert.match(app, /building_representation = "transparent_massing"/);
assert.match(app, /setSceneReviewStatus\("accepted"\)/);
assert.match(app, /setSceneReviewStatus\("changes_requested"\)/);
assert.match(app, /button\.disabled = !hasCurrentWorkflowScene \|\| starterPreview/);
assert.match(assetEditor, /setAssetPreparation\(Object\.freeze\(\{/);
assert.match(assetEditor, /id: "asset-candidates"/);
assert.match(assetEditor, /DEFAULT_ASSET_MANIFEST_NAME = "real_assets_manifest\.jsonl"/);
assert.match(app, /candidate_asset_manifests/);
assert.match(designPanel, /viewer-generation-candidate-list/);
assert.match(baseline, /street_furniture_profile: "none"/);
assert.match(baseline, /amenity_coverage_mode: "off"/);
assert.match(baseline, /curated_street_assets_profile: "disabled"/);
assert.match(baseline, /building_representation: "transparent_massing"/);
assert.match(baseline, /skip_llm: true/);
assert.match(baseline, /randomSeed: 42/);
assert.match(baseline, /render_presentation_artifacts: false/);
assert.match(baseline, /capture_3d_views: false/);
assert.match(publicProject, /shortLabel = baselineIndex === 1 \? "A"/);
assert.match(publicProject, /shortLabel = `B\$\{humanIndex\}`/);
assert.match(publicProject, /shortLabel = `C\$\{candidateIndex\}`/);
assert.match(publicProject, /generation_mode: "parametric"/);
assert.match(publicProject, /goal_weights: goalWeights/);
assert.match(publicProject, /parent_revision_id: parentRevisionId/);
assert.match(scenarios, /PARAMETER \+ SCORE MATRIX/);
assert.match(scenarios, /道路骨架/);
assert.match(scenarios, /街道家具/);
assert.match(scenarios, /data-scenario-action="generate"/);
assert.match(scenarioStyles, /grid-template-columns: minmax\(17rem, 0\.32fr\)/);
assert.match(sceneGraph, /forward_drive_lane_count/);
assert.match(sceneGraph, /bike_lane_count/);
assert.match(sceneGraph, /bus_lane_count/);
assert.match(sceneGraph, /data-strip-field="width_m"/);
assert.match(sceneGraph, /setAnnotationDraft/);
assert.match(sceneGraph, /onNavigateProfessionalScene/);
assert.match(sceneGraph, /sceneMatchesCurrentAnnotation/);
assert.match(sceneGraphShell, /data-admin-source-tools\$\{advancedSourceToolsHidden\}/);
assert.match(sceneGraphShell, /scene-source-open-existing/);
assert.match(sceneGraphShell, /showAdvancedSourceTools\?: boolean/);
assert.match(routeIsland, /user\?\.system_role === "admin"/);
assert.match(routeIsland, /syncAdvancedSourceTools\(\)/);
assert.match(routeIsland, /showAdvancedSourceTools: showAdvancedSourceTools\(\)/);
assert.match(routeIsland, /adminButton\.hidden = !visible/);
assert.doesNotMatch(routeIsland, /professionalSession\.subscribe\(\(\) => \{\s*registerProfessionalNavigation\(\)/);
assert.doesNotMatch(routeIsland, /id: "generate"/);
assert.match(routeIsland, /id: "browse-3d"/);

console.log("professional Y-pipeline contract: ok");
